Description: "This template creates ec2 instance in the default VPC"
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d2614eafc1b0e4d2
      InstanceType: t3.micro
